name: Espressif examples tests
# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  espressif_latest:
    name: latest Docker container
    runs-on: ubuntu-latest
    # This should be a safe limit for the tests to run.
    timeout-minutes: 12
    container:
      image: espressif/idf:latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Espressif IDE and build examples
        run: . /opt/esp/idf/export.sh; IDE/Espressif/ESP-IDF/compileAllExamples.sh
  espressif_v4_4:
    name: v4.4 Docker container
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.4
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Espressif IDE and build examples
        run: . /opt/esp/idf/export.sh; IDE/Espressif/ESP-IDF/compileAllExamples.sh
  espressif_v5_0:
    name: v5.0 Docker container
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.0
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Espressif IDE and build examples
        run: . /opt/esp/idf/export.sh; IDE/Espressif/ESP-IDF/compileAllExamples.sh
