[package]
name = "ws_uring"
version = "0.1.0"
edition = "2021"

[dependencies]
io-uring = "0.6.1"
rustls = "0.23.11"
webpki-roots = "0.26.3"
libc = "0.2"
os_socketaddr = "0.2.5"
thiserror = "1.0.63"
url = "2.5.2"

# TODO
[profile.release]
debug = true
